const express = require('express');
const body_parser = require('body-parser');
const userRouters = require('./routers/user.routers');
const courseRouters = require('./routers/courses.routers');
const courseCateRouters = require('./routers/coursesCategory.routers');
const episodesRouters = require('./routers/episode.routers');
const userSpecialtyRouters = require('./routers/userSpecialty.routers');
const favoriteCoursesRouters = require('./routers/favoriteCourses.routers');
const ratesRouters = require('./routers/rating.routers');
const searchRoutes = require('./routers/search.routers');
const commentsRoutes = require('./routers/comments.routers');
const app = express();

app.use(body_parser.json());
app.use('/api/users', userRouters);
app.use('/api/courses', courseRouters);
app.use('/api/coursesCategory', courseCateRouters);
app.use('/api/episodes', episodesRouters);
app.use('/api/userSpecialty', userSpecialtyRouters);
app.use('/api/fav', favoriteCoursesRouters);
app.use('/api/rate', ratesRouters);
app.use('/api/search', searchRoutes);
app.use('/api/comment', commentsRoutes);
module.exports = app;
